version: "3"
services:
  app:
    image: docker.pkg.github.com/yarmsl/backend-ural_polymer/backend-uralpolymer:develop
    container_name: polydor-server-container
    build:
      context: .
    restart: always
    ports:
    - 5000:5000
