name: Deploy Polydor Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            registry: docker.pkg.github.com
            name: docker.pkg.github.com/yarmsl/backend-ural_polymer/backend-uralpolymer
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: "develop"